### ISSUE TITLE
@ManagedBean is marked deprecated, but the Spec. doc. is not updated

### ISSUE THREAD

**Issue by edbratt** [jakartaee/common-annotations-api#108]
@managedBean was marked deprecated in https://github.com/eclipse-ee4j/common-annotations-api/pull/105 that that was not also reflected in the Spec. text. Spec. text needs to be updated as well.
JavaDoc does include this change. The JavaDocs suggest this is to be replaced with CDI Beans.

**Comment by powerbroker** [comment]
how this could happen, when Jakarta Managed Beans 2.0 is [still active](https://jakarta.ee/specifications/managedbeans/2.0) and refers to the annotation in [2.1.2. Naming](https://jakarta.ee/specifications/managedbeans/2.0/jakarta-managed-beans-spec-2.0.html#a29)??

**Comment by lukasj** [comment]
3.0 removed ManagedBean in #114
