### ISSUE TITLE
Jakarta Annotation 2.1.2 Patch/Service Release Management

### ISSUE THREAD

**Issue by JanWesterkamp-iJUG** [jakartaee/common-annotations-api#117]
While the latest Release Plan for 3.0.0 is passing, there is a requirement for having a Patch/Service Release to fix some CVEs for a potetnial Jakarta EE 10.0.1 release. To prevent additional maintenance work like creating an extra branch and do cherry-picking, these fixes should be merged and released **before** the breaking changes planed in version 3.0.0.

I will create a PR for https://bugs.eclipse.org/bugs/show_bug.cgi?id=581580 soon.
There might be additional fixes necessary, which can be tracked here too.

**Comment by lukasj** [comment]
This is done I guess. Feel free to reopen if not
