### ISSUE TITLE
Which version should I choose?

### ISSUE THREAD

**Issue by chenwenlong-java** [jakartaee/common-annotations-api#125]
When I upgraded from grpc 1.29.0 to 1.59.0, grpc required'org.apache.tomcat: annotations-api: 6.0.53 ', and I used'javax.annotation: javax.annotation-api: 1.3.2' in the original project.
I see that Tomcat implements the Jakarta Annotations specification, so for org.apache.tomcat: annotations-api: 6.0.53, which version of Jakarta Annotations should I choose to maintain their compatibility?

**Comment by lukasj** [comment]
depending on java package names:
* JavaEE8/JakartaEE8 - _javax.annotation_ package namespace -  use jakarta.annotation:jakarta.annotation-api:1.3.5
* JakartaEE 9 - _jakarta.annotation_ package namespace - use jakarta.annotation:jakarta.annotation-api:2.0.0
* JakartaEE 10 - _jakarta.annotation_ package namespace - use jakarta.annotation:jakarta.annotation-api:2.1.1
* JakartaEE 11  - _jakarta.annotation_ package namespace - wait for jakarta.annotation:jakarta.annotation-api:3.0.0

note that 2.1.1 is backward compatible with 2.0.0.

In your particular case, for org.apache.tomcat: annotations-api: 6.0.53 jakarta.annotation:jakarta.annotation-api:1.3.5 is the one to choose
