### ISSUE TITLE
Compatibility Certification Request for Eclipse GlassFish 8.0.0-M3

### ISSUE THREAD

**Issue by lukasj** [jakartaee/common-annotations-api#135]
- [x] Organization Name ("Organization") and, if applicable, URL\
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)\
  [Eclipse GlassFish 8.0.0-M3](https://github.com/eclipse-ee4j/glassfish/releases/tag/8.0.0-M3)
- [x] Specification Name, Version and download URL\
   [Jakarta Annotations 3.0](https://jakarta.ee/specifications/annotations/3.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL\
  [Jakarta Annotations TCK 3.0.0](http://download.eclipse.org/ee4j/ca/jakartaee11/staged/eftl/jakarta-annotations-tck-3.0.0.zip), SHA-256: 9421c6ca66274d32dfb408848f75a42d57f120599fe0d8403c5c5c1141d5ac4d
- [x] Public URL of TCK Results Summary\
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-annotations/3.0/TCK-Results.html)
- [x] Any Additional Specification Certification Requirements\
  None
- [x] Java runtime used to run the implementation\
  Oracle JDK 17.0.2, Oracle JDK 21.0.2
- [x] Summary of the information for the certification environment, operating system, cloud, ...\
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
Do we have a pass on Java 17 as well?

**Comment by lukasj** [comment]
8.0.0-M3 supports SE 21+, would 17 make sense/be valid?

**Comment by ivargrimstad** [comment]
I thought they backed to SE 17 for GlassFish.

**Comment by lukasj** [comment]
the repo is clear - [8.0 branch](https://github.com/eclipse-ee4j/glassfish/blob/8.0/nucleus/parent/pom.xml#L776-L777) says 21, [8.0.0-M3 tag](https://github.com/eclipse-ee4j/glassfish/blob/8.0.0-M3/nucleus/parent/pom.xml#L776-L777) says 21 as well

**Comment by lukasj** [comment]
Accepting by lazy consensus
